"use client";

import { Inter } from "next/font/google";
import { Footer, Header } from "ui";
import { topItems } from "../utils/constants";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header topItems={topItems} />
        <section className="mx-auto mt-[20vh] min-h-[100vh] max-w-[1110px]">
          {children}
        </section>
        <Footer className="max-w-[1110px]" />
      </body>
    </html>
  );
}
